server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"
preview_length = 80

[rofi]
line_length = 30
menu_length = 5
menu_prompt = "Clipboard"
extra_arguments = []

[dmenu]
line_length = 30
menu_length = 5
menu_prompt = "Clipboard"
extra_arguments = [
    "-fn",
    "xos4 Terminus-14",
    "-l",
    "0",
]

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipboard"
extra_arguments = []

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
