repo:
  - changed-files:
    - any-glob-to-any-file: '*'

GitHub-Action:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/*'

Configs:
  - changed-files:
    - any-glob-to-any-file: 'configs/**/*'

Package-Files:
  - changed-files:
    - any-glob-to-any-file: 'packages/**/*'

scripts:
  - changed-files:
    - any-glob-to-any-file: 'scripts/**/*'

debug:
  - changed-files:
    - any-glob-to-any-file: 'scripts/debug/**/*'

helpers:
  - changed-files:
    - any-glob-to-any-file: 'scripts/helpers/**/*'

installers:
  - changed-files:
    - any-glob-to-any-file: 'scripts/installers/**/*'
