# checkov:skip=CKV2_GHA_1: reason="We explicitly need wide permissions"
name: "Combine Dependabot PRs"
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "main"
          openPR: true
          allowSkipped: false
