---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [main, develop]
  push:
    branches-ignore: [main]


permissions:
  contents: read
  statuses: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          FILTER_REGEX_EXCLUDE: "^(docs/|packages/.*\\.md)$"
          SHELL_SHFMT_ARGS: "-i 2 -ci -bn"
